/**
 * The bridge's HTTP surface: `POST /entries`, `GET /entries`, `DELETE
 * /entries/:id` (plus the prototype's body-style `DELETE /entries {id}`, so one
 * transport client works bridge-less against an app-provided endpoint),
 * `GET /healthz`, and the review channel — `GET /events` (SSE to adapters),
 * `POST /reviews` (the agent's held call) and `POST /reviews/:id/verdict`.
 *
 * Loopback only — this is a local dev daemon, never a network service.
 *
 * **The threat model, stated plainly** (docs/design.md "Security"): while this
 * daemon runs, *every page the developer visits* can reach it, because CORS has
 * to be wide open — the whole point of the embed is that it runs on whatever
 * origin the developer's app happens to use, and the extension injects into
 * arbitrary sites. Three things keep that proportionate:
 *
 *   - **Host check.** A request whose `Host` is not loopback is refused, which
 *     is what stops DNS rebinding (`evil.com` resolving to 127.0.0.1 to turn a
 *     cross-origin write into a same-origin read).
 *   - **Caps.** Bodies are capped (413) and `note`/`selector` are capped at the
 *     boundary, so an unbounded POST cannot exhaust the daemon's memory or
 *     stuff an inbox an agent will later read.
 *   - **A token on the review channel.** `GET /events` and
 *     `POST /reviews/:id/verdict` are the human-in-the-loop guarantee: without
 *     a gate, a hostile page could subscribe, learn the reviewId and approve
 *     the developer's review before they ever saw it. The token is generated by
 *     the daemon and handed to adapters out of band (a `.fix-ui.token` file,
 *     the extension's options page, `initFixUi({ token })`).
 *
 * The entries routes stay open by design; the caps above are what carries that
 * risk, and inbox entries are documented as UNTRUSTED agent input.
 *
 * Routes live in a table so later features can register their own and reach
 * shared state through `ctx.server`.
 */
import { timingSafeEqual } from "node:crypto";
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import type { AddressInfo } from "node:net";
import {
  BusyError,
  createReviewBroker,
  DEFAULT_TIMEOUT_SECONDS,
  type ReviewBroker,
  type ReviewOutcome,
  type SurfaceDescription,
} from "./broker.js";
import {
  appendEntry,
  listEntries,
  removeEntry,
  resolveProject,
  type JsonRecord,
} from "./storage.js";
import { packageVersion } from "./version.js";

export const HOST = "127.0.0.1";

/** Comment-line keep-alive for SSE (docs/agent-integration.md): intermediaries
 *  and idle-socket timers must not decide a quiet review is a dead stream. */
const HEARTBEAT_MS = 15_000;

const CORS_HEADERS: Record<string, string> = {
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "GET, POST, DELETE, OPTIONS",
  "access-control-allow-headers": "content-type, x-fixui-token",
};

/** An entry is read by an LLM every time it is acted on, and buffered here
 *  before it is written; both are reasons a page may not send megabytes. */
export const MAX_BODY_BYTES = 256 * 1024;

export interface BridgeServerOptions {
  /** 0 lets the OS pick a free port; the bound port lands on `server.port`. */
  port: number;
  /** Where entries go when the wire carries no `project` — the daemon's cwd. */
  defaultProject: string;
  /**
   * Shared secret for the review channel (`GET /events`,
   * `POST /reviews/:id/verdict`), passed as `?token=` or `x-fixui-token`.
   * Omitted → those routes are open, which is only ever right in a test.
   */
  token?: string;
  /** SSE keep-alive spacing; only tests have a reason to shorten it. */
  heartbeatMs?: number;
}

export interface RouteContext {
  req: IncomingMessage;
  res: ServerResponse;
  url: URL;
  params: Record<string, string>;
  server: BridgeServer;
  json(status: number, payload: unknown): void;
}

export type RouteHandler = (ctx: RouteContext) => void | Promise<void>;

export interface BridgeServer {
  /** The bound port once started (the requested one until then). */
  readonly port: number;
  readonly defaultProject: string;
  /** One broker per daemon — the MCP server calls it in-process. */
  readonly broker: ReviewBroker;
  /** Register a route; `:name` segments become `ctx.params.name`. */
  route(method: string, pattern: string, handler: RouteHandler): void;
  /**
   * Watch inbox mutations; the listener gets the resolved project directory,
   * and the returned function stops watching. Fire-and-forget by contract: a
   * listener that throws or blocks may not affect the HTTP request that caused
   * the change (daemon mode turns this into an MCP `feedback/updated`
   * notification — docs/agent-integration.md).
   */
  onInboxChange(listener: (project: string) => void): () => void;
  start(): Promise<void>;
  stop(): Promise<void>;
}

interface Route {
  method: string;
  segments: string[];
  handler: RouteHandler;
}

export function sendJson(res: ServerResponse, status: number, payload: unknown): void {
  const body = JSON.stringify(payload);
  res.writeHead(status, {
    ...CORS_HEADERS,
    "content-type": "application/json; charset=utf-8",
    "content-length": Buffer.byteLength(body),
  });
  res.end(body);
}

/** Body over `MAX_BODY_BYTES`. Answered as 413 wherever a route reads a body. */
export class PayloadTooLargeError extends Error {
  constructor() {
    super(`request body exceeds ${MAX_BODY_BYTES} bytes`);
    this.name = "PayloadTooLargeError";
  }
}

/**
 * Read a JSON object body. `null` means "not a JSON object" — malformed,
 * a scalar, an array or empty — which is always a 400 at this boundary;
 * `PayloadTooLargeError` is a 413.
 *
 * Past the cap the chunks are dropped rather than buffered, so the memory this
 * can cost is bounded by the cap plus one chunk however much a caller sends.
 * The stream is still drained to the end: on loopback the wasted bytes are
 * nothing next to answering a caller that is still writing its body with a
 * clean 413 instead of a connection reset.
 */
export async function readJsonRecord(req: IncomingMessage): Promise<JsonRecord | null> {
  const chunks: Buffer[] = [];
  let size = 0;
  let overflowed = false;
  for await (const chunk of req) {
    const buffer = chunk as Buffer;
    size += buffer.length;
    if (size > MAX_BODY_BYTES) {
      overflowed = true;
      chunks.length = 0;
      continue;
    }
    chunks.push(buffer);
  }
  if (overflowed) throw new PayloadTooLargeError();
  if (chunks.length === 0) return null;

  let parsed: unknown;
  try {
    parsed = JSON.parse(Buffer.concat(chunks).toString("utf8"));
  } catch {
    return null;
  }
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) return null;
  return parsed as JsonRecord;
}

function isFilledString(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0;
}

function isPositiveNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value) && value > 0;
}

function normalizePath(pathname: string): string {
  return pathname.length > 1 ? pathname.replace(/\/+$/, "") : pathname;
}

function decodeSegment(value: string): string {
  try {
    return decodeURIComponent(value);
  } catch {
    return value; // an undecodable escape is just an id that matches nothing
  }
}

function matchRoute(route: Route, segments: string[]): Record<string, string> | null {
  if (route.segments.length !== segments.length) return null;
  const params: Record<string, string> = {};
  for (const [index, expected] of route.segments.entries()) {
    const actual = segments[index]!;
    if (!expected.startsWith(":")) {
      if (expected !== actual) return null;
      continue;
    }
    if (actual === "") return null;
    params[expected.slice(1)] = decodeSegment(actual);
  }
  return params;
}

function errorText(cause: unknown): string {
  return cause instanceof Error ? cause.message : String(cause);
}

/** Answer a failed request. Inbox failures land here: the message names the
 *  path the bridge tried (docs/design.md "Error handling"). */
function fail(res: ServerResponse, cause: unknown): void {
  if (res.headersSent) res.end();
  else if (cause instanceof PayloadTooLargeError) {
    sendJson(res, 413, { ok: false, error: errorText(cause) });
  } else sendJson(res, 500, { ok: false, error: errorText(cause) });
}

const INVALID_PROJECT = "project must be an absolute path to an existing directory";

/** Caps at the HTTP boundary, mirroring core's own (packages/core/src/entry.ts):
 *  the inbox is an agent's reading list, not a paste bin. */
export const MAX_NOTE = 10_000;
export const MAX_SELECTOR = 2000;

/**
 * What a page may say about itself on `GET /events` (docs/agent-integration.md
 * "Surfaces"). Every one of these lands in a listing an agent reads, so they
 * are capped and stripped like any other browser-authored string — a title is
 * whatever the page set `document.title` to, and a `label` is free text.
 * Truncated rather than refused: a long title is no reason to deny a page the
 * review channel.
 */
export const MAX_SURFACE_TEXT = 300;
export const MAX_SURFACE_URL = 2000;
/** A `surfaceId` is a UUID the bridge itself minted; anything longer is noise. */
const MAX_SURFACE_ID = 200;

/** Control characters are what a hostile page would send: a surface is read
 *  by an agent as one line of description. Strip them, trim, then cap. */
const CONTROL_CHARS = /[\u0000-\u001f\u007f]/g;

function surfaceText(value: string | null, max: number): string | undefined {
  if (value === null) return undefined;
  const cleaned = value.replace(CONTROL_CHARS, "").trim();
  return cleaned === "" ? undefined : cleaned.slice(0, max);
}

/** Chrome's window/tab ids: integers or nothing. */
function surfaceInt(value: string | null): number | undefined {
  if (value === null || value.trim() === "") return undefined;
  const parsed = Number(value);
  return Number.isSafeInteger(parsed) ? parsed : undefined;
}

/** The subscriber's self-description, with only the fields it got right. */
function describeFrom(url: URL): SurfaceDescription {
  const get = url.searchParams.get.bind(url.searchParams);
  const adapter = get("adapter");
  const describe: SurfaceDescription = {};
  const origin = surfaceText(get("origin"), MAX_SURFACE_TEXT);
  const pageUrl = surfaceText(get("url"), MAX_SURFACE_URL);
  const title = surfaceText(get("title"), MAX_SURFACE_TEXT);
  const label = surfaceText(get("label"), MAX_SURFACE_TEXT);
  const windowId = surfaceInt(get("windowId"));
  const tabId = surfaceInt(get("tabId"));
  if (origin !== undefined) describe.origin = origin;
  if (pageUrl !== undefined) describe.url = pageUrl;
  if (title !== undefined) describe.title = title;
  if (label !== undefined) describe.label = label;
  if (adapter === "embed" || adapter === "extension") describe.adapter = adapter;
  if (windowId !== undefined) describe.windowId = windowId;
  if (tabId !== undefined) describe.tabId = tabId;
  return describe;
}

/** Constant-time compare that tolerates unequal lengths. */
function secretEquals(provided: string, expected: string): boolean {
  const a = Buffer.from(provided, "utf8");
  const b = Buffer.from(expected, "utf8");
  // timingSafeEqual throws on a length mismatch, and the length of a token is
  // not the secret — compare against a same-length buffer, then require equal
  // lengths, so a wrong guess costs the same time whatever its length.
  const padded = Buffer.alloc(b.length);
  a.copy(padded);
  return timingSafeEqual(padded, b) && a.length === b.length;
}

export function createBridgeServer(opts: BridgeServerOptions): BridgeServer {
  const routes: Route[] = [];
  const broker = createReviewBroker();
  const heartbeatMs = opts.heartbeatMs ?? HEARTBEAT_MS;
  const inboxListeners = new Set<(project: string) => void>();
  let boundPort = opts.port;
  let http: Server | undefined;

  /** Tell the watchers the inbox changed. Never on the request's critical path:
   *  a broken listener is the listener's problem, not the writer's. */
  function inboxChanged(project: string): void {
    for (const listener of [...inboxListeners]) {
      try {
        listener(project);
      } catch {
        // Nothing to do — the entry is already on disk and answered.
      }
    }
  }

  const api: BridgeServer = {
    get port() {
      return boundPort;
    },
    defaultProject: opts.defaultProject,
    broker,

    route(method, pattern, handler) {
      routes.push({ method, segments: normalizePath(pattern).split("/"), handler });
    },

    onInboxChange(listener) {
      inboxListeners.add(listener);
      return () => {
        inboxListeners.delete(listener);
      };
    },

    start() {
      return new Promise((resolve, reject) => {
        const server = createServer((req, res) => {
          // Nothing a request can do may take the daemon down or leave the
          // connection hanging — always answer, even on our own bugs.
          dispatch(req, res).catch((cause: unknown) => fail(res, cause));
        });
        const onError = (cause: Error): void => reject(cause);
        server.once("error", onError);
        server.listen(opts.port, HOST, () => {
          server.removeListener("error", onError);
          boundPort = (server.address() as AddressInfo).port;
          http = server;
          resolve();
        });
      });
    },

    stop() {
      broker.stop(); // held reviews and their timers die with the daemon
      const server = http;
      if (!server) return Promise.resolve();
      http = undefined;
      return new Promise((resolve, reject) => {
        server.closeAllConnections(); // keep-alive sockets would hold close() open
        server.close((cause) => (cause ? reject(cause) : resolve()));
      });
    },
  };

  /**
   * DNS rebinding is the attack this closes: a name the attacker controls that
   * resolves to 127.0.0.1 makes the browser treat the daemon as same-origin,
   * and every CORS decision above becomes irrelevant. A browser always sends
   * the *name it dialed* as `Host`, so refusing anything but loopback refuses
   * exactly that — and costs a legitimate caller nothing.
   */
  function loopbackHost(req: IncomingMessage): boolean {
    const host = req.headers.host;
    if (typeof host !== "string") return false;
    // The port is part of the check: a rebound name on the right port is still
    // the wrong name. Port 80 is allowed to be implicit, as HTTP requires.
    const allowed =
      boundPort === 80
        ? ["127.0.0.1", "localhost", "127.0.0.1:80", "localhost:80"]
        : [`127.0.0.1:${boundPort}`, `localhost:${boundPort}`];
    return allowed.includes(host.toLowerCase());
  }

  /** The review channel's gate. No configured token → open (tests only). */
  function authorized(req: IncomingMessage, url: URL): boolean {
    const expected = opts.token;
    if (expected === undefined || expected === "") return true;
    // `?token=` as well as the header: `EventSource` cannot set headers, and a
    // header would cost the verdict POST a CORS preflight for nothing.
    const header = req.headers["x-fixui-token"];
    const provided = url.searchParams.get("token") ?? (typeof header === "string" ? header : null);
    return provided !== null && secretEquals(provided, expected);
  }

  async function dispatch(req: IncomingMessage, res: ServerResponse): Promise<void> {
    const url = new URL(req.url ?? "/", `http://${HOST}:${boundPort}`);
    if (!loopbackHost(req)) {
      return sendJson(res, 403, {
        ok: false,
        error: "fixui-bridge serves 127.0.0.1 and localhost only",
      });
    }
    if (req.method === "OPTIONS") {
      // Preflight for every route, including the ones registered later.
      res.writeHead(204, CORS_HEADERS);
      res.end();
      return;
    }

    const segments = normalizePath(url.pathname).split("/");
    for (const route of routes) {
      if (route.method !== req.method) continue;
      const params = matchRoute(route, segments);
      if (!params) continue;
      const ctx: RouteContext = {
        req,
        res,
        url,
        params,
        server: api,
        json: (status, payload) => sendJson(res, status, payload),
      };
      try {
        await route.handler(ctx);
      } catch (cause) {
        fail(res, cause);
      }
      return;
    }

    sendJson(res, 404, { ok: false, error: `no route for ${req.method} ${url.pathname}` });
  }

  /** Query-string project routing for the read/delete side. */
  function projectFromQuery(ctx: RouteContext): string | null {
    return resolveProject(ctx.url.searchParams.get("project"), api.defaultProject);
  }

  api.route("POST", "/entries", async (ctx) => {
    const entry = await readJsonRecord(ctx.req);
    if (!entry) return ctx.json(400, { ok: false, error: "expected a JSON object body" });
    if (!isFilledString(entry.note) || !isFilledString(entry.selector)) {
      return ctx.json(400, { ok: false, error: "entry requires a non-empty note and selector" });
    }
    if (entry.note.length > MAX_NOTE || entry.selector.length > MAX_SELECTOR) {
      return ctx.json(400, {
        ok: false,
        error: `note must be at most ${MAX_NOTE} characters and selector at most ${MAX_SELECTOR}`,
      });
    }

    const project = resolveProject(entry.project, api.defaultProject);
    if (!project) return ctx.json(400, { ok: false, error: INVALID_PROJECT });

    ctx.json(200, { ok: true, entry: await appendEntry(project, entry) });
    inboxChanged(project);
  });

  api.route("GET", "/entries", async (ctx) => {
    const project = projectFromQuery(ctx);
    if (!project) return ctx.json(400, { ok: false, error: INVALID_PROJECT });

    ctx.json(200, { entries: await listEntries(project) });
  });

  api.route("DELETE", "/entries/:id", async (ctx) => {
    const project = projectFromQuery(ctx);
    if (!project) return ctx.json(400, { ok: false, error: INVALID_PROJECT });

    const removed = await removeEntry(project, ctx.params.id!);
    ctx.json(200, { ok: true });
    // Only a real removal is a change: `{ok:true}` also answers an unknown id,
    // and announcing that would make `feedback/updated` mean nothing.
    if (removed) inboxChanged(project);
  });

  // The prototype's body-style delete, kept so one transport client serves both.
  api.route("DELETE", "/entries", async (ctx) => {
    const body = await readJsonRecord(ctx.req);
    const id = body?.id;
    if (!body || (typeof id !== "string" && typeof id !== "number")) {
      return ctx.json(400, { ok: false, error: "delete requires an id" });
    }

    // The client carries `project` in the body here, the way it does on create;
    // the query string is the fallback so curl-style deletes work too.
    const requested = body.project ?? ctx.url.searchParams.get("project");
    const project = resolveProject(requested, api.defaultProject);
    if (!project) return ctx.json(400, { ok: false, error: INVALID_PROJECT });

    const removed = await removeEntry(project, String(id));
    ctx.json(200, { ok: true });
    if (removed) inboxChanged(project);
  });

  // ── The review channel (docs/agent-integration.md "Direction 2") ──────────

  const UNAUTHORIZED = "review channel requires the bridge token (?token= or x-fixui-token)";

  /** The adapter's half: one long-lived SSE stream per page. */
  api.route("GET", "/events", (ctx) => {
    // Gated: a subscriber learns the reviewId, and the reviewId is all it takes
    // to answer the review in the human's place.
    if (!authorized(ctx.req, ctx.url)) return ctx.json(401, { ok: false, error: UNAUTHORIZED });

    const project = projectFromQuery(ctx);
    if (!project) return ctx.json(400, { ok: false, error: INVALID_PROJECT });

    const write = (chunk: string): void => {
      if (!ctx.res.writableEnded && !ctx.res.destroyed) ctx.res.write(chunk);
    };

    ctx.res.writeHead(200, {
      ...CORS_HEADERS,
      "content-type": "text/event-stream; charset=utf-8",
      "cache-control": "no-cache, no-transform",
      connection: "keep-alive",
    });
    // A comment right away flushes the headers, so the page knows it is on.
    write(": connected\n\n");

    const heartbeat = setInterval(() => write(": heartbeat\n\n"), heartbeatMs);
    // The query string is how a page introduces itself, so an agent can tell it
    // apart from the other page on the same project (`GET /surfaces`).
    const unsubscribe = broker.subscribe(
      project,
      { send: (event, data) => write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`) },
      describeFrom(ctx.url),
    );
    ctx.res.on("close", () => {
      clearInterval(heartbeat);
      unsubscribe();
    });
    // No `end()`: the stream stays open until the page goes away.
  });

  /**
   * What the developer has open, so an agent can aim a review at ONE page
   * instead of every page of a project (docs/agent-integration.md "Surfaces").
   *
   * Gated like `/events`: this discloses which sites, which windows and which
   * page titles are on the developer's screen, and a `surfaceId` is what a
   * targeted review needs. `?project=` scopes it; without one it answers every
   * surface, which is how an agent finds the page it never mapped.
   */
  api.route("GET", "/surfaces", (ctx) => {
    if (!authorized(ctx.req, ctx.url)) return ctx.json(401, { ok: false, error: UNAUTHORIZED });

    const requested = ctx.url.searchParams.get("project");
    if (requested === null || requested === "") {
      return ctx.json(200, { surfaces: broker.listSurfaces() });
    }
    const project = resolveProject(requested, api.defaultProject);
    if (!project) return ctx.json(400, { ok: false, error: INVALID_PROJECT });
    ctx.json(200, { surfaces: broker.listSurfaces(project) });
  });

  /**
   * The agent's half: held open, answered only when the review resolves.
   *
   * Deliberately NOT token-gated. A proxy instance (a second `fixui-bridge` in
   * another project's cwd) posts here, and it has no way to read the daemon's
   * token file — gating this route would break the one-daemon-many-projects
   * shape for no gain: without `/events` an attacker can create a review but
   * never see its id, and the human is the one who answers it.
   */
  api.route("POST", "/reviews", async (ctx) => {
    const body = await readJsonRecord(ctx.req);
    if (!body) return ctx.json(400, { ok: false, error: "expected a JSON object body" });
    if (!isFilledString(body.prompt)) {
      return ctx.json(400, { ok: false, error: "review requires a non-empty prompt" });
    }

    const timeout = body.timeoutSeconds;
    if (timeout !== undefined && !isPositiveNumber(timeout)) {
      return ctx.json(400, {
        ok: false,
        error: "timeoutSeconds must be a positive number of seconds (fractions allowed)",
      });
    }

    const surfaceId = body.surfaceId;
    if (surfaceId !== undefined && !isFilledString(surfaceId)) {
      return ctx.json(400, {
        ok: false,
        error: "surfaceId must be a non-empty string from GET /surfaces",
      });
    }

    const project = resolveProject(body.project, api.defaultProject);
    if (!project) return ctx.json(400, { ok: false, error: INVALID_PROJECT });

    // The agent can vanish while we hold its call — Ctrl-C, a harness restart,
    // a dead proxy. Watch `res`, not `req`: a fully-read request stream closes
    // the moment its body is consumed (above), while the response closes either
    // when we answer or when the connection dies under us. Answering closes it
    // too, so the broker ends only the review this request still owns.
    const agentGone = new AbortController();
    ctx.res.on("close", () => agentGone.abort());

    let outcome: ReviewOutcome;
    try {
      outcome = await broker.requestReview({
        project,
        prompt: body.prompt,
        ...(typeof body.url === "string" ? { url: body.url } : {}),
        ...(surfaceId === undefined ? {} : { surfaceId: surfaceId.slice(0, MAX_SURFACE_ID) }),
        timeoutSeconds: timeout ?? DEFAULT_TIMEOUT_SECONDS,
        signal: agentGone.signal,
      });
    } catch (cause) {
      if (!(cause instanceof BusyError)) throw cause;
      return ctx.json(409, { ok: false, error: "busy" });
    }

    // Minutes may have passed: the agent could have walked away from the call.
    if (ctx.res.writableEnded || ctx.res.destroyed) return;
    ctx.json(200, outcome);
  });

  /** The page's answer. It carries only the review id — the pending review is
   *  what names the project, so no routing argument is needed here. */
  api.route("POST", "/reviews/:reviewId/verdict", async (ctx) => {
    // Gated: this is the human-in-the-loop guarantee. Anyone who can post here
    // can approve the developer's review before the developer has seen it.
    if (!authorized(ctx.req, ctx.url)) return ctx.json(401, { ok: false, error: UNAUTHORIZED });

    const body = await readJsonRecord(ctx.req);
    if (!body) return ctx.json(400, { ok: false, error: "expected a JSON object body" });

    const verdict = body.verdict;
    if (verdict !== "approved" && verdict !== "changes") {
      return ctx.json(400, { ok: false, error: 'verdict must be "approved" or "changes"' });
    }

    const entryIds = body.entryIds;
    if (!Array.isArray(entryIds) || entryIds.some((id) => typeof id !== "string")) {
      return ctx.json(400, { ok: false, error: "entryIds must be an array of entry ids" });
    }

    const resolved = await broker.submitVerdict(ctx.params.reviewId!, verdict, entryIds as string[]);
    if (!resolved) {
      return ctx.json(404, { ok: false, error: `no pending review ${ctx.params.reviewId}` });
    }
    ctx.json(200, { ok: true });
  });

  api.route("GET", "/healthz", (ctx) => {
    ctx.json(200, { ok: true, name: "fixui-bridge", version: packageVersion() });
  });

  return api;
}
